// Copyright Aisssky

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace CP_Tags 
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(None);

	namespace Status
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dead);
	}
	namespace Hero
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mage);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Assassin);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Doctor);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Archer);
	}

	namespace GamePhase
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lobby);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CharacterSelect);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PreGame);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InProgress);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PostGame);
	}
	namespace SetByCaller
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Projectile);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
	}

	namespace CPAbilities
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateOnGiven);

		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Secondary);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tertiary);

		namespace Shared
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Q);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(R);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(E);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shift);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Respawn);
		}
		namespace Enemy
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack);
		}
		namespace Player
		{
			namespace Warrior
			{
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Q);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(R);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(E);
			}
			namespace Assassin
			{
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Q);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(R);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(E);
			}
			namespace Mage
			{
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Q);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(R);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(E);
			}
			namespace Doctor
			{
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Q);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(R);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(E);
			}
			namespace Archer
			{
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Q);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(R);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(E);
			}
		}
	}

	namespace Events
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(KillScored);

		namespace Player
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Death);
		}

		namespace Enemy
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(EndAttack);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MeleeTraceHit);
		}

		namespace Combat
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Q_Impact);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Impact);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(E_Impact);
		}
	}
}