;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="CPTags.Cooldown.Archer.E",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Archer.Q",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Archer.R",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Assassin",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Assassin.E",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Assassin.Q",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Assassin.R",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Doctor.E",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Doctor.Q",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Doctor.R",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Mage",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Mage.E",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Mage.Q",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Mage.R",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Secondary",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Warrior.E",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Warrior.Q",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Warrior.R",DevComment="")
+GameplayTagList=(Tag="CPTags.Cooldown.Warrior.Shift",DevComment="")
+GameplayTagList=(Tag="CPTags.CPAbilities.BlockHitReact",DevComment="")
+GameplayTagList=(Tag="CPTags.CPAbilities.Death",DevComment="")
+GameplayTagList=(Tag="CPTags.CPAbilities.Enemy.HitReact",DevComment="")
+GameplayTagList=(Tag="CPTags.Events.Player.Primary",DevComment="")
+GameplayTagList=(Tag="CPTags.Events.Player.SecondaryAbility",DevComment="")
+GameplayTagList=(Tag="CPTags.Hero.Archer",DevComment="")
+GameplayTagList=(Tag="CPTags.Hero.Assassin",DevComment="")
+GameplayTagList=(Tag="CPTags.Hero.Doctor",DevComment="")
+GameplayTagList=(Tag="CPTags.Hero.Mage",DevComment="")
+GameplayTagList=(Tag="CPTags.Hero.Warrior",DevComment="")
+GameplayTagList=(Tag="CPTags.SetByCaller.Damage.Burn",DevComment="")
+GameplayTagList=(Tag="CPTags.SetByCaller.Damage.Poison",DevComment="")
+GameplayTagList=(Tag="CPTags.SetByCaller.Heal.Base",DevComment="")
+GameplayTagList=(Tag="CPTags.SetByCaller.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="CPTags.SetByCaller.Player.Secondary",DevComment="")
+GameplayTagList=(Tag="CPTags.Status.Dead",DevComment="")
+GameplayTagList=(Tag="GameplayCue.BurstImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.HitReact",DevComment="")

